"""empty message

Revision ID: e2d56f3475
Revises: None
Create Date: 2015-02-18 16:04:58.867227

"""

# revision identifiers, used by Alembic.
revision = 'e2d56f3475'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('complete_by', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    ### end Alembic commands ###
